//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niacomsoft.ProductiveLibrary.Resources.Internal {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Niacomsoft.ProductiveLibrary.Resources.Internal.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0005: 字符串参数 “{0}” 不可以为 NULL 或空字符串。 的本地化字符串。
        /// </summary>
        public static string ArgumentException_string_null_or_empty_with_argument_name {
            get {
                return ResourceManager.GetString("ArgumentException_string_null_or_empty_with_argument_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0004: 字符串参数不可以为 NULL 或空字符串。 的本地化字符串。
        /// </summary>
        public static string ArgumentException_string_null_or_empty_without_argument_name {
            get {
                return ResourceManager.GetString("ArgumentException_string_null_or_empty_without_argument_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0007: 字符串参数 “{0}” 不可以为 NULL 、空字符串或空格符。 的本地化字符串。
        /// </summary>
        public static string ArgumentException_string_null_or_whitespace_with_argument_name {
            get {
                return ResourceManager.GetString("ArgumentException_string_null_or_whitespace_with_argument_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0006: 字符串参数不可以为 NULL 、空字符串或空格符。 的本地化字符串。
        /// </summary>
        public static string ArgumentException_string_null_or_whitespace_without_argument_name {
            get {
                return ResourceManager.GetString("ArgumentException_string_null_or_whitespace_without_argument_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0003: 缺少了一个必需的参数 “{0}”。 的本地化字符串。
        /// </summary>
        public static string ArgumentNullException_with_argument_name {
            get {
                return ResourceManager.GetString("ArgumentNullException_with_argument_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0002: 缺少了一个必需的参数。 的本地化字符串。
        /// </summary>
        public static string ArgumentNullException_without_argument_name {
            get {
                return ResourceManager.GetString("ArgumentNullException_without_argument_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危急 的本地化字符串。
        /// </summary>
        public static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试 的本地化字符串。
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0001: 应用程序抛出了一个未处理的异常。 的本地化字符串。
        /// </summary>
        public static string Exception_default_message {
            get {
                return ResourceManager.GetString("Exception_default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0008: 尝试获取多语言支持资源字符串时，引发了一个未处理的异常。 的本地化字符串。
        /// </summary>
        public static string ResourceStringException_default_message {
            get {
                return ResourceManager.GetString("ResourceStringException_default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 追踪 的本地化字符串。
        /// </summary>
        public static string Trace {
            get {
                return ResourceManager.GetString("Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
