//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niacomsoft.ProductiveLibrary.Resources.Internal {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Niacomsoft.ProductiveLibrary.Resources.Internal.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0016: Wrong derivation. The type &quot;{0}&quot; is not derived from &quot;{1}&quot;. 的本地化字符串。
        /// </summary>
        public static string ArgumentException_invalid_inheritance {
            get {
                return ResourceManager.GetString("ArgumentException_invalid_inheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0005: The string parameter &quot;{0}&quot; cannot be NULL or an empty string. 的本地化字符串。
        /// </summary>
        public static string ArgumentException_string_null_or_empty_with_argument_name {
            get {
                return ResourceManager.GetString("ArgumentException_string_null_or_empty_with_argument_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0004: String parameters cannot be NULL or empty. 的本地化字符串。
        /// </summary>
        public static string ArgumentException_string_null_or_empty_without_argument_name {
            get {
                return ResourceManager.GetString("ArgumentException_string_null_or_empty_without_argument_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0007: The string parameter &quot;{0}&quot; cannot be NULL, empty , or white-spaces. 的本地化字符串。
        /// </summary>
        public static string ArgumentException_string_null_or_whitespace_with_argument_name {
            get {
                return ResourceManager.GetString("ArgumentException_string_null_or_whitespace_with_argument_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0006: String parameters can&apos;t be NULL, empty , or white-spaces. 的本地化字符串。
        /// </summary>
        public static string ArgumentException_string_null_or_whitespace_without_argument_name {
            get {
                return ResourceManager.GetString("ArgumentException_string_null_or_whitespace_without_argument_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0003: A required parameter &quot;{0}&quot; is missing. 的本地化字符串。
        /// </summary>
        public static string ArgumentNullException_with_argument_name {
            get {
                return ResourceManager.GetString("ArgumentNullException_with_argument_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0002: A required parameter is missing. 的本地化字符串。
        /// </summary>
        public static string ArgumentNullException_without_argument_name {
            get {
                return ResourceManager.GetString("ArgumentNullException_without_argument_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0011: The parameter &quot;{0}&quot; is outside the specified range. 的本地化字符串。
        /// </summary>
        public static string ArgumentOutOfRangeException_with_argument_name {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_with_argument_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0012: The parameter &quot;{0}&quot; is outside the specified range &quot;{1}&quot;. 的本地化字符串。
        /// </summary>
        public static string ArgumentOutOfRangeException_with_argument_name_and_range {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_with_argument_name_and_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0014: The parameter is outside the specified range of &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        public static string ArgumentOutOfRangeException_without_argument_name {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_without_argument_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0013: The parameter is outside the specified range. 的本地化字符串。
        /// </summary>
        public static string ArgumentOutOfRangeException_without_argument_name_and_range {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_without_argument_name_and_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical 的本地化字符串。
        /// </summary>
        public static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLT0015: The default text encoder has been changed to &quot;{0} - {1}&quot;. 的本地化字符串。
        /// </summary>
        public static string Diagnostics_default_encoding_reset {
            get {
                return ResourceManager.GetString("Diagnostics_default_encoding_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLD0010: The parameter value is a NULL value, and the &quot;ifNull&quot; parameter value will be used instead, please pay attention. 的本地化字符串。
        /// </summary>
        public static string Diagnostics_inherit_from {
            get {
                return ResourceManager.GetString("Diagnostics_inherit_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLD0009: The parameter value is a NULL value, please pay attention. 的本地化字符串。
        /// </summary>
        public static string Diagnostics_message_isnull {
            get {
                return ResourceManager.GetString("Diagnostics_message_isnull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0001: The application threw an unhandled exception. 的本地化字符串。
        /// </summary>
        public static string Exception_default_message {
            get {
                return ResourceManager.GetString("Exception_default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLX0008: An unhandled exception was thrown when trying to get a multi-language support resource string. 的本地化字符串。
        /// </summary>
        public static string ResourceStringException_default_message {
            get {
                return ResourceManager.GetString("ResourceStringException_default_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trace 的本地化字符串。
        /// </summary>
        public static string Trace {
            get {
                return ResourceManager.GetString("Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
