<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  <Import
    Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"
    Condition="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../')) != ''" />
  <PropertyGroup>
    <TargetFrameworks>$(TargetFrameworks)</TargetFrameworks>
    <Description>基于 UnityContainer 动态解析服务依赖关系的核心类库。A core class library based on UnityContainer to dynamically resolve service dependencies.</Description>
    <AssemblyName>$(AssemblyName).Core.UnityContainer</AssemblyName>
    <RootNamespace>$(RootNamespace)</RootNamespace>
    <PackageTags>core; service-resolver; unity-container; $(PackageTags)</PackageTags>
  </PropertyGroup>

  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>