<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  <Import
    Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"
    Condition="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../')) != ''" />
  <PropertyGroup>
    <TargetFrameworks>$(TargetFrameworks)</TargetFrameworks>
    <Description>基于 NLog 的，记录运行时诊断日志的方法集 NLog-based method set for logging runtime diagnostic logs.</Description>
    <AssemblyName>$(AssemblyName).Logging.NLog</AssemblyName>
    <RootNamespace>$(RootNamespace).Runtime.Diagnostics</RootNamespace>
    <PackageTags>runtime; diagnostic; logging; nlog; nlog-project; $(PackageTags)</PackageTags>
  </PropertyGroup>

  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>